name: artifact

on:
  push:
    tags:
      - v*.*.*

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Build artifact
      run: make linux_zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: github-apps-token-swift-linux
        path: github-apps-token-linux.zip

  macos:
    runs-on: macos-15

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Create artifactbundle for macOS
      run: ./scripts/artifactbundle.sh

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: github-apps-token-swift-macos
        path: GitHubAppsToken.artifactbundle.zip
