name: artifact

on:
  push:
    tags:
      - v*.*.*

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build artifact
      run: make linux_zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-apps-token-swift-linux
        path: github-apps-token-linux.zip

  macos:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Create artifactbundle for macOS
      run: ./scripts/artifactbundle.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-apps-token-swift-macos
        path: GitHubAppsToken.artifactbundle.zip
