name: Renovate

on:
  pull_request:

jobs:
  swift-package-resolve:
    runs-on: macos-14
    if: startswith(github.head_ref, 'renovate')

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Swift Package resolve
      run: swift package resolve
    - name: Git config
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/tuist/xcbeautify
        version: '*'
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1 | xcbeautify
    - name: Commit & push
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git add Package.resolved
        if git commit -m "Resolve Swift Package [ci skip]"; then
          git push origin "HEAD:${HEAD_REF}"
        fi
