name: Test

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: xcode-27

    env:
      DEVELOPER_DIR: /Applications/Xcode_27.0.app/Contents/Developer

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1 | xcbeautify --renderer github-actions

  ubuntu:
    runs-on: ubuntu-26.04-arm
    container: swift:6.4.0

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install xcbeautify
      run: |
        apt-get update && apt-get install -y build-essential
        git clone https://github.com/cpisciotta/xcbeautify.git
        cd xcbeautify
        make install
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1 | xcbeautify --renderer github-actions
