name: Test

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: Cyberbeni/install-swift-tool@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        url: https://github.com/tuist/xcbeautify
        version: '*'
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1 | xcbeautify
    - name: Docker image
      if: matrix.os == 'ubuntu-latest'
      run: make docker_image
