name: Test

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1 | xcbeautify

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run test
      run: |
        set -o pipefail
        swift test 2>&1
    - name: Docker image
      run: make docker_image
